services:
  db_server:
    image: mysql:${MYSQL_IMAGE_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      TZ: ${TIME_ZONE}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    container_name: db_server
    hostname: db_server

  game_server:
    image: liuguangw/game_server:latest
    restart: always
    volumes:
      - ./home:/home
    working_dir: /home
    environment:
      TZ: ${TIME_ZONE}
      GAME_SERVER_IP: ${GAME_SERVER_IP}
      GAME_SERVER_PORT: ${GAME_SERVER_PORT}
      SMU_INTERVAL: ${SMU_INTERVAL}
      DATA_INTERVAL: ${DATA_INTERVAL}
      WITH_GAME_LOG: ${WITH_GAME_LOG}
      BILLING_SERVER_IP: ${BILLING_SERVER_IP}
      BILLING_SERVER_PORT: ${BILLING_SERVER_PORT}
    secrets:
      - DB_PASSWORD
    ports:
      - "${GAME_SERVER_LOGIN_PORT}:7384"
      - "${GAME_SERVER_PORT}:${GAME_SERVER_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
    cap_add:
      - ALL
    privileged: true
    container_name: game_server
    hostname: game_server
    depends_on:
      - db_server

secrets:
  DB_PASSWORD:
    file: db_password.txt